### PR TITLE
[MPOM-247] make minimum Maven version configurable via property

### PR DESCRIPTION
**Pull request by kwin**
"mavenVersion"

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — APPROVED** [review]

**Comment by rfscholte** [comment]
There are 2 different meanings for mavenVersion:
- The version required to build the project
- The maven compatible version

We use the property for the latter, i.e. using it for dependency versions.

It is very good possible to require Maven4 to create a Maven 3.1 compatible plugin.

So I'm -1

**Comment by kwin** [comment]
The property name `mavenVersion` was suggested by @slachiewicz, but I am open for other suggestions to make the intention clearer. What about `mavenRequiredVersionForBuild`?

**Comment by rfscholte** [comment]
Just a proposal: `<minimalMavenBuildVersion>${mavenVersion}</minimalMavenBuildVersion>`
Still quite a long name, though

**Comment by kwin** [comment]
@rfscholte Do you have any examples of usages of `mavenVersion`? I would like to add some comment to make the differences between the two properties clearer. At least in ASF Parent there is no usage of `mavenVersion`.

**Comment by rfscholte** [comment]
It is not done at any parent level, but on plugin level. The reason is that prerequisites are not inherited, so you need to define them per plugin.
But that does make my proposal awkward, I see now.

**Comment by kwin** [comment]
I now use `minimalMavenBuildVersion`, but give it a literal default value, as property `mavenVersion` is not defined in this scope.

**Comment by kwin** [comment]
@rfscholte Are you fine with this PR?

**Review by rfscholte — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #431

**Pull request closed without merging**
