### PR TITLE
[MPOM-263] enforce minimum Java build version 8

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — CHANGES_REQUESTED** [review]
The ticket title must contain the enforced Java version.

**Comment by kwin** [comment]
@michael-o Are you referring to the JIRA issue title, the commit message or both?

**Comment by michael-o** [comment]
Both.

**Comment by kwin** [comment]
The JIRA issue title was slightly different anyways:`Enforce building with Java8+`, I just adjusted the commit message in https://github.com/apache/maven-apache-parent/commit/c9930fbc660df5188680683f3503750cfb3c3223.

**Comment by michael-o** [comment]
This is better now...

**Review by michael-o — APPROVED** [review]

**Pull request merged**
