### PR TITLE
[MPOM-438] Bump maven-plugin-plugin from 3.9.0 to 3.10.2

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by slachiewicz** [comment]
this plugin version depends on plexus-xml 4.

**Comment by ctubbsii** [comment]
> this plugin version depends on plexus-xml 4.

I didn't understand this comment from @slachiewicz , so I did some digging to see if this was a problem. I see that this plugin has a direct explicit (not provided, runtime, or optional) dependency on `org.apache.maven.plugin-tools:maven-plugin-tools-api:jar:3.10.1`, which has a direct explicit (not provided, runtime, or optional) dependency on `org.codehaus.plexus:plexus-xml:jar:4.0.0`.

<details>
<summary>In the `mvn dependency:tree` for this plugin, I don't see it as a transitive dependency of any other dependencies for this plugin (click to expand):
</summary>

```
[INFO] --- dependency:3.4.0:tree (default-cli) @ maven-plugin-plugin ---
[INFO] org.apache.maven.plugins:maven-plugin-plugin:maven-plugin:3.10.1
[INFO] +- org.apache.maven:maven-core:jar:3.2.5:provided
[INFO] |  +- org.apache.maven:maven-settings:jar:3.2.5:provided
[INFO] |  +- org.apache.maven:maven-settings-builder:jar:3.2.5:provided
[INFO] |  +- org.apache.maven:maven-model-builder:jar:3.2.5:provided
[INFO] |  +- org.apache.maven:maven-aether-provider:jar:3.2.5:provided
[INFO] |  |  \- org.eclipse.aether:aether-spi:jar:1.0.0.v20140518:provided
[INFO] |  +- org.eclipse.aether:aether-impl:jar:1.0.0.v20140518:provided
[INFO] |  +- org.eclipse.aether:aether-api:jar:1.0.0.v20140518:provided
[INFO] |  +- org.eclipse.aether:aether-util:jar:1.0.0.v20140518:provided
[INFO] |  +- org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.3:provided
[INFO] |  |  +- javax.inject:javax.inject:jar:1:runtime
[INFO] |  |  +- aopalliance:aopalliance:jar:1.0:provided
[INFO] |  |  \- com.google.guava:guava:jar:16.0.1:provided
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:provided
[INFO] |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:provided
[INFO] |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:provided
[INFO] |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:provided
[INFO] |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:provided
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-api:jar:3.10.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.1.1:compile
[INFO] |  |  \- org.apache.maven.doxia:doxia-sink-api:jar:1.11.1:compile
[INFO] |  |     \- org.apache.maven.doxia:doxia-logging-api:jar:1.11.1:compile
[INFO] |  +- org.codehaus.plexus:plexus-xml:jar:4.0.0:compile
[INFO] |  |  \- org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile
[INFO] |  |     \- org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile
[INFO] |  |        \- org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.4:compile
[INFO] |  \- org.codehaus.plexus:plexus-java:jar:1.1.2:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-generators:jar:3.10.1:compile
[INFO] |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  +- org.ow2.asm:asm:jar:9.5:compile
[INFO] |  +- org.ow2.asm:asm-commons:jar:9.5:compile
[INFO] |  |  \- org.ow2.asm:asm-tree:jar:9.5:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.16.1:compile
[INFO] |  \- net.sf.jtidy:jtidy:jar:r938:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-java:jar:3.10.1:runtime
[INFO] |  \- com.thoughtworks.qdox:qdox:jar:2.0.3:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-annotations:jar:3.10.1:runtime
[INFO] |  +- org.codehaus.plexus:plexus-archiver:jar:4.8.0:runtime
[INFO] |  |  +- org.codehaus.plexus:plexus-io:jar:3.4.1:runtime
[INFO] |  |  +- commons-io:commons-io:jar:2.13.0:runtime
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.23.0:runtime
[INFO] |  |  +- org.iq80.snappy:snappy:jar:0.4:runtime
[INFO] |  |  +- org.tukaani:xz:jar:1.9:runtime
[INFO] |  |  \- com.github.luben:zstd-jni:jar:1.5.5-5:runtime
[INFO] |  \- org.ow2.asm:asm-util:jar:9.5:runtime
[INFO] |     \- org.ow2.asm:asm-analysis:jar:9.5:runtime
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.10.1:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-ant:jar:3.10.1:runtime
[INFO] |  \- org.apache.maven.plugin-tools:maven-plugin-tools-model:jar:3.10.1:runtime
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-tools-beanshell:jar:3.10.1:runtime
[INFO] |  \- org.apache-extras.beanshell:bsh:jar:2.0b6:runtime
[INFO] +- org.apache.maven:maven-plugin-api:jar:3.2.5:provided
[INFO] +- org.apache.maven:maven-model:jar:3.2.5:provided
[INFO] +- org.apache.maven:maven-repository-metadata:jar:3.2.5:provided
[INFO] +- org.apache.maven:maven-artifact:jar:3.2.5:provided
[INFO] +- org.codehaus.plexus:plexus-utils:jar:4.0.0:compile
[INFO] +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:provided
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.2:provided
[INFO] |  +- javax.enterprise:cdi-api:jar:1.2:provided
[INFO] |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:provided
[INFO] +- org.codehaus.plexus:plexus-velocity:jar:1.2:compile
[INFO] |  \- commons-collections:commons-collections:jar:3.1:compile
[INFO] +- org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.10.0:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.0:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.0:test
[INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.0:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.0:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.10.0:test
[INFO] +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] +- org.apache.maven.plugin-tools:maven-script-beanshell:jar:3.10.1:test
[INFO] |  \- org.codehaus.plexus:plexus-bsh-factory:jar:1.0-alpha-7:test
[INFO] |     +- classworlds:classworlds:jar:1.1-alpha-2:test
[INFO] |     \- bsh:bsh:jar:1.3.0:test
[INFO] \- org.apache.maven.plugin-tools:maven-script-ant:jar:3.10.1:test
[INFO]    +- org.apache.ant:ant:jar:1.10.13:test
[INFO]    +- org.apache.ant:ant-launcher:jar:1.10.13:test
[INFO]    \- org.codehaus.plexus:plexus-ant-factory:jar:1.0-alpha-2.1:test
```

</details>

So, I think this isn't a problem, and I'm not sure what the intent of the comment was.

**Comment by slawekjaranowski** [comment]
We have conflict in plexus-xml on some classes only, until plugin doesn't use it - it is not problem.
I assume that all tests pass in plugin it is not a problem.

**Comment by slawekjaranowski** [comment]
@slachiewicz I have checked this versions with Maven 3.9.5 and 4.x ... and I don't any issues
- generated plugin descriptor is the same
- documentation site is also generated in proper way

**Comment by slachiewicz** [comment]
If it works for you, that's good. I can see only that we pulled the below dependencies:

[INFO] |  |  \- org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile
[INFO] |  |     \- org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile
[INFO] |  |        \- org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile

@hboutemy wdyt?

**Comment by slawekjaranowski** [comment]
> If it works for you, that's good. I can see only that we pulled the below dependencies:
> 
> [INFO] | | - org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:compile [INFO] | | - org.apache.maven:maven-api-xml:jar:4.0.0-alpha-5:compile [INFO] | | - org.apache.maven:maven-api-meta:jar:4.0.0-alpha-5:compile
> 
> @hboutemy wdyt?

I know about a few more dependencies ... but I hope it not affect for working

**Comment by slawekjaranowski** [comment]
@slachiewicz we have 3.10.2 - with plexus-xml 3.0.0
https://maven.apache.org/plugin-tools/maven-plugin-plugin/dependencies.html

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #382

**Pull request merged**
