### PR TITLE
[MPOM-456] Bump surefire/failsafe from 3.2.2 to 3.2.5

### PR DESCRIPTION
**Pull request by ctubbsii**
This supersedes #178 and #186

### CODE REVIEW

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slachiewicz** [comment]
Superseded by #186

**Comment by ctubbsii** [comment]
> Superseded by #186

No. #186 is still incorrect, as it is updating the wrong property. I've updated this PR to the newer version, so it should supersede #186 as well now.

**Review by slachiewicz — APPROVED** [review]

**Comment by ctubbsii** [comment]
Resolved conflicts. Somebody with write permission should really merge this so it doesn't keep drifting.

**Comment by jira-importer** [comment]
Resolve #389

**Pull request merged**
