### PR TITLE
[MPOM-286] org.apache:apache should conform with needed Sonatype checksums on deployment

### PR DESCRIPTION
**Pull request by Tibor17**

### CODE REVIEW

**Comment by Tibor17** [comment]
@slawekjaranowski
Here is the improvement. Maybe we should ping the team.

**Review by michael-o — COMMENTED** [review]
Why? Isn't it enough to have it in the release profile only?

**Comment by Tibor17** [comment]
@michael-o
I changed to checksum-maven-plugin. Not the GPG.

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
Don't do it in this way. `gpg-plugin` must be only in `apache-release` profile otherwise we will have problem with all build. 

Probably gpg is only configured on local machines, and I suppose that only for more advanced users, usually is not configured, so many contributors may have such problem like in GH checks for this PR.

This change don't resolve your problem.

**Comment by Tibor17** [comment]
@slawekjaranowski 
Check the commit again, I am moving only `checksum-maven-plugin`, not the GPG.

**Comment by michael-o** [comment]
I still don't understand the purpose of this for non-releases.

**Comment by slawekjaranowski** [comment]
I afraid that sha-512 is not required for Sonatype ...

it only create signature for artifact with classifier `source-release` ... but source-release is created in apache-release profile.

**Comment by kwin** [comment]
What issue are you trying to solve here? Neither ASFs Nexus nor Maven Central require SHA-512 checksums

**Comment by hboutemy** [comment]
so really, no, don't do this, because:
1. the need is not clear (not to say wrong, which is what I think currently)
2. the implementation is wrong: you're trying to calculate a checksum for an artifact that is created only in apache-release profile

if you want to use apache-release profile with a SNAPSHOT, don't hesitate to do it: it perfectly works

what is currently defined in apache-release profile is consistent: please don't break this consistency

**Comment by slawekjaranowski** [comment]
@Tibor17 - can we closed it?

**Comment by jira-importer** [comment]
Resolve #498

**Pull request closed without merging**
