### PR TITLE
[MPOM-332] Bump maven-deploy-plugin from 2.8.2 to 3.0.0

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
I'm not sure if it safe especially with G level metadata updates for plugins

**Comment by slachiewicz** [comment]
You mean some feature or existing bug?

**Comment by kwin** [comment]
https://issues.apache.org/jira/browse/MNG-7055?

**Comment by jira-importer** [comment]
Resolve #504

**Pull request closed without merging**
